### ISSUE TITLE
Gallery extends too far on Revisioner Page index

### ISSUE THREAD

**Issue by TrainsRAwesome** [TrainsRAwesome/Infinity-Website#10]
On certain screen resolutions, while still being a small screen but using index instead of index_smallscreen for `revisioner/`, the gallery extends too far, creating a purple bar.

**Comment by TrainsRAwesome** [comment]
well unless anyone has a screen width < 300 pixels it works, and I doubt anyone is going to be using that resolution.

_According to the Worldwide Screen Resolution Stats (Jan 2020 – Jan 2021), the most commonly used resolutions across mobile, desktop, and tablet are:
- 1920×1080 (8.89%)
- 1366×768 (8.44%)
- 360×640 (7.28%)
- 414×896 (4.58%)
- 1536×864 (3.88%)
- 375×667 (3.75%)_

**There is still a purple bar on pages 600 < screen_width < 750, which can be fixed by redirecting to mobile version. This is an issue with the large screen view, not mobile view.**

**Comment by Diacius** [comment]
hmm i’ll have a look when i can

**Comment by Diacius** [comment]
I've made some changes to the viewport meta tags, this may help to fix any issues

**Comment by TrainsRAwesome** [comment]
yeah seems to mostly be fixed, I will fiddle with the pixel widths for changing to mobile later.

**Comment by TrainsRAwesome** [comment]
Fixed (font scaling issue).
Some font scaling issues though still do remain on the revisioner page.
