### ISSUE TITLE
Rick roll doesn't work any more

### ISSUE THREAD

**Issue by TrainsRAwesome** [TrainsRAwesome/Infinity-Website#11]
External link for rick roll doesn't work any more.
Maybe we should embed YT instead (although ads would be a problem)

**Comment by TrainsRAwesome** [comment]
This has been fixed in the latest commit - thx @Diacius

**Comment by Diacius** [comment]
yh sorry i forgot to close this, it was just a broken url. loads from archive.org so it should be good now
