### ISSUE TITLE
Convert px font sizes to responsive font sizes

### ISSUE THREAD

**Issue by Diacius** [TrainsRAwesome/Infinity-Website#12]
Instead of using pixel font sizes use `rem` or `em`
In `styles.css` a lot of styling is done with `px`
**Doing this will help remove the need for two seperate indexes**

**Comment by TrainsRAwesome** [comment]
Oh the main reason for different indexes was due to the arrangement and complete re-modification of image galleries on certain pages

**Comment by TrainsRAwesome** [comment]
done on index
