### ISSUE TITLE
Remove all element styling

### ISSUE THREAD

**Issue by Diacius** [TrainsRAwesome/Infinity-Website#13]
Move any element styled like this
```html
<div style="/*Styling*/"></div>
``` 
Into CSS files If this was moved to CSS files it would be far easier to fix issues

**Comment by TrainsRAwesome** [comment]
okay yeah needa fix that

**Comment by TrainsRAwesome** [comment]
Being fixed on an ongoing basis - stuff like this is removed when pages are renovated
